spring:
  # H2 DB
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
    ddl-auto: none
    generate-ddl: true

  main:
    allow-circular-references: true

handlebars:
  suffix: .html
  expose-session-attributes: true